# Generated by Django 4.0 on 2021-12-15 19:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
                ('menuCarts', django.db.models.manager.Manager()),
            ],
        ),
    ]
