# Generated by Django 4.0 on 2021-12-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_restaurant_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='menucart',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuCarts', to='api.restaurant'),
        ),
    ]
