# Generated by Django 4.0 on 2021-12-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_menucart_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelistproduct',
            name='priceList',
        ),
        migrations.RemoveField(
            model_name='pricelistproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='priceList',
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
        migrations.DeleteModel(
            name='PriceListProduct',
        ),
    ]
