# Generated by Django 4.0 on 2021-12-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_productorder_prize_product_prize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prize',
            new_name='price',
        ),
    ]
