# Generated by Django 4.0 on 2021-12-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_prize_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucart',
            name='products',
            field=models.ManyToManyField(related_name='products', to='api.Product'),
        ),
    ]
